name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOTNET_VERSION: '9.0.x'
  NODE_VERSION: '20.x'

jobs:
  backend-build-test:
    name: Backend Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      working-directory: ./backend
      run: dotnet restore

    - name: Build
      working-directory: ./backend
      run: dotnet build --no-restore --configuration Release

    - name: Test
      working-directory: ./backend
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Publish
      working-directory: ./backend
      run: dotnet publish src/TaskBoard.Api/TaskBoard.Api.csproj -c Release -o ./publish

  frontend-build-test:
    name: Frontend Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      working-directory: ./frontend
      run: pnpm install --frozen-lockfile

    - name: Lint
      working-directory: ./frontend
      run: pnpm run lint || echo "Lint not configured"

    - name: Build
      working-directory: ./frontend
      run: pnpm run build

    - name: Test
      working-directory: ./frontend
      run: pnpm run test:ci || echo "Tests not configured"

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [backend-build-test, frontend-build-test]
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Backend Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: false
        tags: taskboard-backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Frontend Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./frontend/Dockerfile
        push: false
        tags: taskboard-frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    environment:
      name: staging
      url: https://staging.taskboard.example.com

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Staging
      run: |
        echo "🚀 Deploying to staging environment..."
        # Add your staging deployment commands here
        # Example: kubectl apply -f k8s/staging/
        # Or: docker-compose -f docker/docker-compose.staging.yml up -d

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: production
      url: https://taskboard.example.com

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Production
      run: |
        echo "🚀 Deploying to production environment..."
        # Add your production deployment commands here
        # Example: kubectl apply -f k8s/production/
        # Or: docker-compose -f docker/docker-compose.prod.yml up -d
